# Generated by Django 2.2.4 on 2019-08-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('IdEvent', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('CONFERENCIA', 'Conferencia'), ('SEMINARIO', 'Seminario'), ('CONGRESO', 'Congreso'), ('CURSO', 'Curso')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField()),
                ('finishDate', models.DateTimeField()),
                ('presencial', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], max_length=50)),
            ],
        ),
    ]
